[supervisord]
nodaemon=true                 ; Ejecutar Supervisor en primer plano (requerido por Docker)
loglevel=info                 ; Nivel de log para Supervisor
pidfile=/var/run/supervisord.pid

[program:php-fpm]
command=/usr/local/sbin/php-fpm -F --pid /var/run/php-fpm.pid -y /usr/local/etc/php-fpm.conf
autostart=true
autorestart=true
priority=5
stdout_logfile=/dev/stdout    ; Redirigir stdout de php-fpm al stdout del contenedor
stdout_logfile_maxbytes=0     ; Sin límite de tamaño para el log de stdout
stderr_logfile=/dev/stderr    ; Redirigir stderr de php-fpm al stderr del contenedor
stderr_logfile_maxbytes=0     ; Sin límite de tamaño para el log de stderr
;user=www-data                 ; Ejecutar php-fpm como usuario www-data
numprocs=1
process_name=%(program_name)s_%(process_num)02d
stopwaitsecs=10
stopsignal=QUIT

[program:nginx]
command=/usr/sbin/nginx -g 'daemon off;' ; Ejecutar Nginx en primer plano
autostart=true
autorestart=true
priority=10
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
user=root                     ; El proceso maestro de Nginx corre como root

; Descomenta y configura si usas colas de Laravel y quieres un worker gestionado por Supervisor:
; [program:laravel-worker]
; process_name=%(program_name)s_%(process_num)02d
; command=php /var/www/html/artisan queue:work --sleep=3 --tries=3 --max-time=3600
; autostart=true
; autorestart=true
; stopwaitsecs=3600
; numprocs=1 ; Ajusta el número de workers
; user=www-data
; stdout_logfile=/var/www/html/storage/logs/worker-stdout.log ; O redirigir a /dev/stdout
; stderr_logfile=/var/www/html/storage/logs/worker-stderr.log ; O redirigir a /dev/stderr
